import { ROLES } from "./constants.js";

export const PERMISSIONS = {
  START_MEETING: [ROLES.HOST],
  END_MEETING: [ROLES.HOST],

  APPROVE_USER: [ROLES.HOST, ROLES.CO_HOST],
  REJECT_USER: [ROLES.HOST, ROLES.CO_HOST],

  PROMOTE_COHOST: [ROLES.HOST],

  MUTE_USER: [ROLES.HOST, ROLES.CO_HOST],
  KICK_USER: [ROLES.HOST, ROLES.CO_HOST],

  PUBLIC_CHAT_SEND: [ROLES.HOST, ROLES.CO_HOST, ROLES.PARTICIPANT],
  PRIVATE_CHAT_SEND: [ROLES.HOST, ROLES.CO_HOST],

  SCREEN_SHARE_START: [ROLES.HOST, ROLES.CO_HOST],
};
