import { ROLES } from "./constants.js";

export const PERMISSIONS = {
  // Meeting lifecycle
  START_MEETING: [ROLES.HOST],
  END_MEETING: [ROLES.HOST],

  // Waiting room
  APPROVE_USER: [ROLES.HOST, ROLES.CO_HOST],
  REJECT_USER: [ROLES.HOST, ROLES.CO_HOST],

  // Role management
  PROMOTE_COHOST: [ROLES.HOST],

  // Moderation
  FORCE_MUTE: [ROLES.HOST, ROLES.CO_HOST],
  KICK_USER: [ROLES.HOST, ROLES.CO_HOST],

  // Chat
  PUBLIC_CHAT_SEND: [ROLES.HOST, ROLES.CO_HOST, ROLES.PARTICIPANT],
  PRIVATE_CHAT_SEND: [ROLES.HOST, ROLES.CO_HOST],

  // Screen sharing
  SCREEN_SHARE_START: [ROLES.HOST, ROLES.CO_HOST],
  SCREEN_SHARE_STOP: [ROLES.HOST, ROLES.CO_HOST],
};
